In [1]:
import pandas as pd 
import json

In [11]:
csv_file = pd.read_csv('/Users/nalex2023/Downloads/references_spreadsheet - Sheet1.csv')

csv_file_removed = csv_file.dropna(axis=0,how='any', subset=['Approximate lat', 'Approximate lon'])

csv_file_removed2 = csv_file_removed.dropna(axis=0,how='any', subset=['Year'] )

csv_file_removed2

,Unnamed: 0,Study Region,Approximate lat,Approximate lon,Year,Observation type,Keywords for the timeline schematic (variables used),Method (can hide this column after plotting),Thresholds,Reference
8,Narayanan,"Thumba, India",8.533333,76.866667,1966,Surface,"Surface winds, Wind reversals",Surface winds,NaN,https://doi.org/10.54302/mausam.v18i4.4704
9,Hamza and Babu,"Cochin, India",9.966667,76.283333,2007,NaN,"Sea breeze circulation, Monsoon boundary layer...",Surface winds,NaN,NaN
10,Rani et al.,West coast of India,10.833333,76.000000,2010,NaN,"Sea/Land Breeze Circulation, High-resolution R...",Surface winds,NaN,NaN
11,Nair et al.,"Thumba, India",8.500000,76.900000,2011,NaN,"Coastal Atmospheric Boundary Layer, Sea Breeze...",Surface winds,NaN,NaN
12,Subrahamanyam et al.,"Thumba, India",8.500000,76.900000,2011,NaN,"Annular Solar Eclipse, Boundary-layer processe...",Surface winds,NaN,NaN
13,Anurose,"Thumba, India",8.500000,76.900000,2011,NaN,"Sea breeze circulation, Vertical structure of ...",Surface winds,NaN,NaN
14,KiranKumar et al.,"Visakhapatnam, India",17.000000,83.300000,2019,NaN,Seasonal variation of sea breeze,Surface winds,NaN,https://doi.org/10.1016/j.jastp.2019.01.013
15,Reddy et al.,"Meenambakkam, India",13.000000,80.060000,2021,NaN,"Thermal internal boundary layer, Sea breeze ch...",Surface winds,NaN,https://doi.org/10.1007/s00703-020-00746-1
16,Williams et al.,"Chennai, India",12.810000,80.030000,2022,NaN,"Sea breeze, black carbon aerosols, aerosol opt...",Surface winds,NaN,https://doi.org/10.1007/s00024-022-03102-z
17,North et al.,"Bengkulu Airport, Sumatra",-3.860000,102.340000,2025,NaN,"Maritime Continent, Diurnal effects, Sea breez...",Surface winds,NaN,NaN
19,Guille et al.,Global,-,-,"2003, 2005",Scatterometer,"Satterometry, Satellites, Global, Satellite-de...",Satellite-derived winds,NaN,NaN
20,Brown et al.,"Darwin, Australia",-12.414800,130.882930,2017,"Scatterometer, Regional atmospheric model outputs","Convection, Mesoscale, ASCAT, land-breeze, off...",Satellite-derived winds,NaN,NaN
22,Watts,"Thorney Island, United Kingdom",50.816000,-0.918400,1955,Surface,"Wind direction, Temperature",Surface winds and temperature,NaN,NaN
23,Biggs and Graves,"Western shore of Lake Erie, United States",42.040140,-83.255250,1962,Surface,"Wind speed, Temperature",Surface winds and temperature,NaN,NaN
24,Lyons,"Chicago, United States",41.855997,-87.605164,1972,Surface,"Wind speed, Temperature",Surface winds and temperature,NaN,NaN
25,Steyn and Faulkner,"Lower Fraser Valley, Canada",43.033333,-123.166667,1986,Surface,"Wind direction, Wind speed, Temperature",Surface winds and temperature,NaN,NaN
26,Laird et al.,"Lake Michigan, United States",42.014610,-87.904360,2001,Surface,"Wind direction, Wind speed, Temperature",Surface winds and temperature,NaN,NaN
27,Lensky and Dayan,East Mediterranean,31.873601,34.707193,2012,"Surface, Infrared satellite imagery","Wind direction, Wind speed, Temperature",Multiple surface parameters,NaN,NaN
28,Xiao et al.,"Tianjin, China",39.040000,117.720000,2023,Surface,"Wind direction, Temperature",Surface winds and temperature,NaN,NaN
29,Guo et al.,"Qingdao, China",36.070000,120.330000,2023,Surface,"Wind direction, Wind speed, Temperature",Surface winds and temperature,NaN,NaN
31,Miller and Keim,"Central New England coast, United States",43.335670,-72.524270,2003,Surface,"Wind direction, Cloud cover, Precipitation",Multiple surface parameters,NaN,NaN
32,Azorin-Molina et al.,"Bay of Alicante, Spain",38.345000,-0.486000,2011,Surface,"Wind speed, Wind direction, Temperature, Humid...",Multiple surface parameters,NaN,NaN
33,Xia et al.,Northeastern coast of the United States,40.710000,-74.010000,2022,Model outputs,"Wind speed, Wind direction, Temperature, Sea l...",Multiple surface parameters,NaN,NaN
34,Bao et al.,Southeastern United States,34.000000,-81.000000,2023,"Reanalysis, Satellite, Radar","Wind direction, Humidity, Cloud bands, High re...",Multiple surface parameters,NaN,NaN
42,Damato et al.,"English Channel and Dover Strait, western Europe",50.398285,0.559993,2003,Visible satellite imagery,On-screen digitising technique,Satellite/Radar observations,NaN,NaN
43,Planchon et al.,Northeastern Brazil,-4.411236,-38.372044,2006,Visible satellite imagery,On-screen digitising technique,Satellite/Radar observations,NaN,NaN
44,Corpetti and Planchon,Brazilian coast,-4.973696,-36.986152,2011,Visible satellite imagery,Snake algorithm,Satellite/Radar observations,NaN,NaN
46,Ferdiansyah et al.,"Jakarta, Indonesia",-6.124000,106.846000,2020,Visible satellite imagery,Snake algorithm,Satellite/Radar observations,NaN,NaN
47,Allagbe et al.,"Gulf of Guinea, West Africa",4.000000,5.000000,2025,Visible satellite imagery,Snake algorithm,Satellite/Radar observations,NaN,NaN
49,Sokolov et al. 2020,"Dunkirk, France",51.040000,2.370822,2020,AI/ML,"Supervised learning, Wind speed, Wind directio...",NaN,NaN,https://journals.ametsoc.org/view/journals/ato...
50,Roy et al. 2022,"Dunkirk, France",51.030000,2.370000,2022,AI/ML,"Supervised learning, Wind speed, Wind directio...",NaN,NaN,https://cnrs.hal.science/hal-04435883/document
51,Krishnamoorthy et al. (2023),Gulf of Khambhat in the Amreli district of Guj...,-71.669000,-20.775000,2023,AI/ML,"Supervised learning, Wind speed, Wind directio...",NaN,NaN,https://papers.ssrn.com/sol3/papers.cfm?abstra...
52,Allagbe et al. (2025),Gulf of Guinea in West Africa,4.000000,5.000000,2025,AI/ML,"Clustering, Snake algorithm",Satellite/Radar observations,NaN,https://www.scirp.org/journal/paperinformation...

In [39]:
csv_file_removed2['id'] = range(1, len(csv_file_removed2) + 1)

csv_file_removed2['Title'] = csv_file_removed2['Observation type']

csv_file_removed2['Authors'] = csv_file_removed2['Unnamed: 0']

csv_file_removed2['Year'] = csv_file_removed2['Year'].astype(int,errors='ignore')

csv_file_removed2['Author Keywords'] = csv_file_removed2['Observation type']
csv_file_removed2['Source'] = 'dummy source'

final_df = csv_file_removed2[['id', 'Title', 'Authors', 'Year', 'Author Keywords', 'Source',]]

/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/209087341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_file_removed2['id'] = range(1, len(csv_file_removed2) + 1)
/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/209087341.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_file_removed2['Title'] = csv_file_removed2['Observation type']
/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/209087341.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_file_removed2['Authors'] = csv_file_removed2['Unnamed: 0']
/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/209087341.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_file_removed2['Year'] = csv_file_removed2['Year'].astype(int,errors='ignore')
/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/209087341.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_file_removed2['Author Keywords'] = csv_file_removed2['Observation type']
/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/209087341.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  csv_file_removed2['Source'] = 'dummy source'

In [40]:
final_df['Title'] = final_df['Title'].str.replace(',', ';')

/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/227541657.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Title'] = final_df['Title'].str.replace(',', ';')

In [44]:
final_df['Title'] = final_df['Title'].fillna('Surface')

final_df['Author Keywords'] = final_df['Author Keywords'].fillna('Surface')

final_df['Author Keywords'] = final_df['Author Keywords'].str.replace(',', ';')


final_df

/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/2850483966.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Title'] = final_df['Title'].fillna('Surface')
/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/2850483966.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Author Keywords'] = final_df['Author Keywords'].fillna('Surface')
/var/folders/bt/kswp83jx5mj4bn1bjkh9g4rsg_b7ks/T/ipykernel_14713/2850483966.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df['Author Keywords'] = final_df['Author Keywords'].str.replace(',', ';')

,id,Title,Authors,Year,Author Keywords,Source
8,1,Surface,Narayanan,1966,Surface,dummy source
9,2,Surface,Hamza and Babu,2007,Surface,dummy source
10,3,Surface,Rani et al.,2010,Surface,dummy source
11,4,Surface,Nair et al.,2011,Surface,dummy source
12,5,Surface,Subrahamanyam et al.,2011,Surface,dummy source
13,6,Surface,Anurose,2011,Surface,dummy source
14,7,Surface,KiranKumar et al.,2019,Surface,dummy source
15,8,Surface,Reddy et al.,2021,Surface,dummy source
16,9,Surface,Williams et al.,2022,Surface,dummy source
17,10,Surface,North et al.,2025,Surface,dummy source
19,11,Scatterometer,Guille et al.,"2003, 2005",Scatterometer,dummy source
20,12,Scatterometer; Regional atmospheric model outputs,Brown et al.,2017,Scatterometer; Regional atmospheric model outputs,dummy source
22,13,Surface,Watts,1955,Surface,dummy source
23,14,Surface,Biggs and Graves,1962,Surface,dummy source
24,15,Surface,Lyons,1972,Surface,dummy source
25,16,Surface,Steyn and Faulkner,1986,Surface,dummy source
26,17,Surface,Laird et al.,2001,Surface,dummy source
27,18,Surface; Infrared satellite imagery,Lensky and Dayan,2012,Surface; Infrared satellite imagery,dummy source
28,19,Surface,Xiao et al.,2023,Surface,dummy source
29,20,Surface,Guo et al.,2023,Surface,dummy source
31,21,Surface,Miller and Keim,2003,Surface,dummy source
32,22,Surface,Azorin-Molina et al.,2011,Surface,dummy source
33,23,Model outputs,Xia et al.,2022,Model outputs,dummy source
34,24,Reanalysis; Satellite; Radar,Bao et al.,2023,Reanalysis; Satellite; Radar,dummy source
42,25,Visible satellite imagery,Damato et al.,2003,Visible satellite imagery,dummy source
43,26,Visible satellite imagery,Planchon et al.,2006,Visible satellite imagery,dummy source
44,27,Visible satellite imagery,Corpetti and Planchon,2011,Visible satellite imagery,dummy source
46,28,Visible satellite imagery,Ferdiansyah et al.,2020,Visible satellite imagery,dummy source
47,29,Visible satellite imagery,Allagbe et al.,2025,Visible satellite imagery,dummy source
49,30,AI/ML,Sokolov et al. 2020,2020,AI/ML,dummy source
50,31,AI/ML,Roy et al. 2022,2022,AI/ML,dummy source
51,32,AI/ML,Krishnamoorthy et al. (2023),2023,AI/ML,dummy source
52,33,AI/ML,Allagbe et al. (2025),2025,AI/ML,dummy source

In [45]:
final_df.to_csv('/Users/nalex2023/main/LSB_main/Review_Paper/sample_test_dft.csv', index=False)